export const PING_TIME_MS = 1000;
export const PING_TIME_SECONDS = PING_TIME_MS * 60;
export const PING_TIME_MINUTES = PING_TIME_SECONDS * 60;
export const PING_TIME_HOURS = PING_TIME_MINUTES * 60;
export const PING_TIME_DAYS = PING_TIME_HOURS * 24;
